config/routes.rb
SampleApp::Application.routes.draw do
  
 
  resources :event_registrations
  resources :relationships, only: [:create, :destroy]
  resources :events
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',   to: 'users#new',            via: 'get'
  match '/signin',   to: 'sessions#new',         via: 'get'
  match '/signout',  to: 'sessions#destroy',     via: 'delete'
  match '/create',   to: 'events#new',           via: 'get'
  match '/help',     to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',   via: 'get'
  match '/contact',  to: 'static_pages#contact', via: 'get'
  match '/prog',     to: 'static_pages#prog',    via: 'get'
  match '/classes',  to: 'static_pages#classes', via: 'get'
  match '/announcements',  to: 'static_pages#announcements', via: 'get' 

end

app/models/association.rb
class Association < ActiveRecord::Base
	belongs_to :user, class_name: "User"
	belongs_to :event, class_name: "Event"
	validates :user_id, presence: true
	validates :event_id, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base	
  has_many :bookings
  has_many :reverse_associations, foreign_key: "event_id",
                                  class_name: "Association",
                                  dependent: :destroy
  has_many :users, through: :reverse_associations, source: :user
  has_many :event_registrations
  has_many :users, through: :event_registrations


def following?(other_event)
    associations.find_by(event_id: other_event.id)
  end

  def follow!(other_event)
    associations.create!(event_id: other_event.id)
  end

  def unfollow!(other_event)
    associations.find_by(event_id: other_event.id).destroy
  end
end

app/models/event_booking.rb
class EventBooking < ActiveRecord::Base
  belongs_to :event_registration
  
end

app/models/event_registration.rb
class EventRegistration < ActiveRecord::Base
  belongs_to :event
  belongs_to :user

  accepts_nested_attributes_for :event
  accepts_nested_attributes_for :user
end

app/models/lesson_booking.rb
class LessonBooking < ActiveRecord::Base
  belongs_to :lesson_registration
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :relationships, dependent: :destroy
  has_many :event_events, through: :associations, source: :event
  has_many :event_registrations
  has_many :events, through: :event_registrations
  

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.paginate(page: params[:page])
	end

    def show
    	@event = Event.find(params[:id])
	end

	def destroy
		Event.find(params[:id]).destroy
    	redirect_to events_url
    end

	def create
        @event = Event.new(event_params)

		if @event.save
			redirect_to events_url
		else
			render 'new'
		end
	end

	def trying
		Event.find(id).users << current_user	
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])

		if @event.save
			redirect_to @event
    	else
      		render 'edit'
    	end
	end

	def new
		@event = Event.new
    end

    private        

    def event_params
    	params.require(:event).permit(:title, :Venue, :Time, :Date)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out  
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def new
  	@user = User.new
  end
  
  def show
  	@user = User.find(params[:id])
  end

  def edit
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

 def update
    if @user.update_attributes(user_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @relationships = @user.relationships.paginate(page: params[:page])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Tennis Website"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/event_bookings_helper.rb
module EventBookingsHelper
end

app/helpers/event_registrations_helper.rb
module EventRegistrationsHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/lesson_bookings_helper.rb
module LessonBookingsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless current_user
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<li>
    <%= link_to event.title, event %>
    | <%= link_to "delete", event, method: :delete %>
    | <%= link_to "sign up" %>

</li>


   

app/views/events/edit.html.erb
<div class="hero-unit">
<% provide(:title, "Create Event") %>


<h1>Create a new Event</h1>


<div class="row">
  <div class="span6 offset3">
    <%= form_for(@event) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :Title %>
      <%= f.text_field :Title %>

      <%= f.label :, :Venue %>
      <%= f.text_field :Venue %>

      <%= f.label :Date %>
      <%= f.text_field :Date %>

      <%= f.label :Time %>
      <%= f.text_field :Time %>


      <%= f.submit "Create Event", class: "btn btn-large btn-primary" %>
    <% end %>

    </div>  
  </div>
</div>

app/views/events/index.html.erb
<div class="hero-unit">
<% provide(:title, 'All Events') %>
<h1>All Events</h1>

<body>
<%= will_paginate %>

<ul class="events">
    <%= render @events %>
</ul>

<%= will_paginate %>

</body>

</div>

app/views/events/new.html.erb
<div class="hero-unit">
<% provide(:title, 'Create New Event') %>
<h1>Create New Event</h1>


<div class="row">
  <div class="span6 offset3">
    <%= form_for(@event) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :Venue %>
      <%= f.text_field :Venue %>

      <%= f.label :Date %>
      <%= f.text_field :Date %>

      <%= f.label :Time %>
      <%= f.text_field :Time %>

      <%= f.submit "Create Event", class: "btn btn-large btn-primary" %>

      <p>Create a new week <%= link_to "New week" %></p>
    <% end %>
  </div>
</div>
</div>

app/views/events/show.html.erb
<div class="hero-unit">
<p>Mike Martin Tennis Academy has been running tennis classes since 2006 and have a 
  reputation for delivering quality coaching. At a young age, we teach essential skills 
  for any sports people using the mini-tennis programme. Technique, racket skills, balance,
  coordination and matchplay will all be experienced on the course. A great opportunity for
  your child to meet other children with similar interests and to spend the summer playing sport outdoors!</p>

<p>

<p><h3>Event Details</h3></p>



	<div class=" panel text ">
		<div class="row">
			
	   	 <div class="eight columns">
	   	 
		 	<div class="row"><h4 class="span8">Title: </h4><p>  <%= @event.title %></div></br></p>
			<div class="row"><h4 class="span8">Venue : </h4><p> <%= @event.Venue %> </div></br></p>
		</div>
	</div>


</br>
<a class="button medium radius alert nice"" onclick="_gaq.push(['_trackEvent', 'Buttons', 'Download theme', 'Homepage']);""  <%= link_to 'Back', events_path %> </a>






 <a class="button medium radius success"" onclick="_gaq.push(['_trackEvent', 'Buttons', 'Download theme', 'Homepage']);""  <%= link_to "Place Booking", new_event_registration_path(:event_id=> @event.id) %></a>


</br></br></br></br>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  <% end %>

</li>

app/views/users/edit.html.erb
<div class="hero-unit">
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="hero-unit">
<% provide(:title, 'All users') %>
<h1>All users</h1>

<body>
<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>
</body>

</div>

app/views/users/new.html.erb
<div class="hero-unit">
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="hero-unit">
<% provide(:title, @user.name) %>
<div class="row">
   <div class="span8">
    <% if @user.relationships.any? %>
      <h3>Posts (<%= @user.relationships.count %>)</h3>
      <ol class="relationships">
        <%= render @relationships %>
      </ol>
      <%= will_paginate @relationships %>
    <% end %>
</div>
</div>
</div>