config/routes.rb
SampleApp::Application.routes.draw do
  
 
  resources :event_registrations
  resources :relationships, only: [:create, :destroy]
  resources :events
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',   to: 'users#new',            via: 'get'
  match '/signin',   to: 'sessions#new',         via: 'get'
  match '/signout',  to: 'sessions#destroy',     via: 'delete'
  match '/create',   to: 'events#new',           via: 'get'
  match '/help',     to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',   via: 'get'
  match '/contact',  to: 'static_pages#contact', via: 'get'
  match '/prog',     to: 'static_pages#prog',    via: 'get'
  match '/classes',  to: 'static_pages#classes', via: 'get'
  match '/announcements',  to: 'static_pages#announcements', via: 'get' 

end

app/models/association.rb
class Association < ActiveRecord::Base
	belongs_to :user, class_name: "User"
	belongs_to :event, class_name: "Event"
	validates :user_id, presence: true
	validates :event_id, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base	
  has_many :bookings
  has_many :reverse_associations, foreign_key: "event_id",
                                  class_name: "Association",
                                  dependent: :destroy
  has_many :users, through: :reverse_associations, source: :user
  has_many :event_registrations
  has_many :users, through: :event_registrations


def following?(other_event)
    associations.find_by(event_id: other_event.id)
  end

  def follow!(other_event)
    associations.create!(event_id: other_event.id)
  end

  def unfollow!(other_event)
    associations.find_by(event_id: other_event.id).destroy
  end
end

app/models/event_booking.rb
class EventBooking < ActiveRecord::Base
  belongs_to :event_registration
  
end

app/models/event_registration.rb
class EventRegistration < ActiveRecord::Base
  belongs_to :event
  belongs_to :user

  accepts_nested_attributes_for :event
  accepts_nested_attributes_for :user
end

app/models/lesson_booking.rb
class LessonBooking < ActiveRecord::Base
  belongs_to :lesson_registration
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :relationships, dependent: :destroy
  has_many :event_events, through: :associations, source: :event
  has_many :event_registrations
  has_many :events, through: :event_registrations
  

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.paginate(page: params[:page])
	end

    def show
    	@event = Event.find(params[:id])
	end

	def destroy
		Event.find(params[:id]).destroy
    	redirect_to events_url
    end

	def create
        @event = Event.new(event_params)

		if @event.save
			redirect_to events_url
		else
			render 'new'
		end
	end

	def trying
		Event.find(id).users << current_user	
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])

		if @event.save
			redirect_to @event
    	else
      		render 'edit'
    	end
	end

	def new
		@event = Event.new
    end

    private        

    def event_params
    	params.require(:event).permit(:title, :Venue, :Time, :Date)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def new
  	@user = User.new
  end
  
  def show
  	@user = User.find(params[:id])
  end

  def edit
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

 def update
    if @user.update_attributes(user_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @relationships = @user.relationships.paginate(page: params[:page])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Tennis Website"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/event_bookings_helper.rb
module EventBookingsHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/lesson_bookings_helper.rb
module LessonBookingsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless current_user
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Website by Patrick Cowan
  </small>
  <nav>
    <ul>
      <li><%= link_to "Terms and Conditions",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand">
        <img src="/assets/Mikem.png"/>
      <nav>
        <ul class="nav pull-right">
          <a class="brand"><img src="/assets/book.png"/>
          <a class="brand"><img src="/assets/facebook.png"/>
          <a class="brand"><img src="/assets/twitter.png"/></a>

        </ul>
        </nav>            
    </div>
  </div>

<header class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav pull-left">
       <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Classes", classes_path %></li>
          <li><%= link_to "About Us", about_path %></li>
           <li><%= link_to "Contact", contact_path %></li>
           <li><%= link_to "Announcements", announcements_path %></li>
            <li><a>News</a></li>
        </ul>
      <nav>
        <ul class="nav pull-right">
         
          <% if signed_in? && current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
            <%end%>
            <% if signed_in? %>
            <li><%= link_to "Online Booking", events_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if signed_in? && current_user.admin? %>
                <li><%= link_to "Create Event", create_path %></li>
                <%end%>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</div>
</header>

  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>


    <div class="container">
      <%= yield %>
       <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_relationship_form.html.erb
<div class="hero-unit">
<%= form_for(@relationship) do |f| %>
  <div class="field">
    <%= f.text_area :address, placeholder: "Write your address..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.user_id_users.count %>
    </strong>
    following
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.relationships.count, "relationship") %>
</span>